apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nginx-deamonset
  namespace: nginx
spec:
  # replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      name: nginx-deamon-pod
      labels:
        app: nginx
    spec:  # <-- spec should be at the same level as metadata
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80

