kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: apache-rolebinding
  namespace: apache
subjects:
- kind: User
  name: apache-manager
  apiGroup: ""
roleRef:
  kind: Role
  name: apache-role
  apiGroup: rbac.authorization.k8s.io
