kind: Pod
apiVersion: v1
metadata:
  name: sidecar-ctr
spec:
  volumes:
    - name: shared-logs
      emptyDir: {}
  containers:
    - name: main-ctr
      image: busybox:latest
      command: ["sh","-c","while true; do echo 'Hello' >> /var/log/app.log; sleep 5; done"]
      volumeMounts:
        - name: shared-logs
          mountPath: /var/log/

    - name: sidecar-ctr
      image: busybox:latest
      command: ["sh","-c","tail -f/var/log/app/log"]
      volumeMounts:
        - name: shared-logs
          mountPath: /var/log/
